# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id_lineup', models.CharField(max_length=45, unique=True)),
                ('week', models.IntegerField()),
                ('budget', models.IntegerField(default=500000000)),
                ('id_starter1', models.IntegerField(default=0, unique=True)),
                ('id_starter2', models.IntegerField(default=0, unique=True)),
                ('id_starter3', models.IntegerField(default=0, unique=True)),
                ('id_starter4', models.IntegerField(default=0, unique=True)),
                ('id_starter5', models.IntegerField(default=0, unique=True)),
                ('id_starter6', models.IntegerField(default=0, unique=True)),
                ('id_starter7', models.IntegerField(default=0, unique=True)),
                ('id_starter8', models.IntegerField(default=0, unique=True)),
                ('id_starter9', models.IntegerField(default=0, unique=True)),
                ('id_starter10', models.IntegerField(default=0, unique=True)),
                ('id_starter11', models.IntegerField(default=0, unique=True)),
                ('id_bench1', models.IntegerField(default=0, unique=True)),
                ('id_bench2', models.IntegerField(default=0, unique=True)),
                ('id_bench3', models.IntegerField(default=0, unique=True)),
                ('id_contest', models.CharField(max_length=45, unique=True)),
                ('id_user', models.IntegerField(unique=True)),
                ('captain', models.IntegerField(default=0, unique=True)),
            ],
        ),
    ]
