# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id_contest', models.CharField(max_length=45, unique=True)),
                ('title', models.CharField(default='Contest', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_admin', models.BooleanField(default=True)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('minimum_participants', models.IntegerField(default=3, max_length=10)),
                ('maximum_participants', models.IntegerField(default=100, max_length=10)),
            ],
        ),
    ]
