# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='maximum_participants',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='contest',
            name='minimum_participants',
            field=models.IntegerField(default=3),
        ),
    ]
