# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name_1', models.CharField(max_length=120)),
                ('last_name_2', models.CharField(default='', max_length=120)),
                ('country', models.CharField(default='', max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateTimeField()),
                ('photo', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
