# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank='true', default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_2',
            field=models.CharField(blank='true', default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank='true', default='', max_length=300),
        ),
    ]
