# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_shirt', models.CharField(max_length=255)),
                ('player_number', models.IntegerField(blank=True, default=0)),
                ('player_birth', models.DateTimeField(blank=True)),
                ('player_value', models.FloatField(default=100000)),
                ('player_position_category', models.CharField(default='position_category3', max_length=18)),
                ('player_link', models.URLField(blank=True, max_length=255)),
                ('id_country', models.CharField(blank=True, max_length=3)),
                ('id_club', models.CharField(blank=True, max_length=45)),
                ('photo', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
